### PR TITLE
add hints issue - timer added

### PR DESCRIPTION
**Pull request by Prajwal2204**
a timer has been added to the hangman game..

a word of length b/w 0 and 5 => 60 secs
a word of length b/w 5 and 10 => 120 secs
a word of length 10 and above => 300 secs

also, you can decrease the timer for testing so as to save time :)

### CODE REVIEW

**Comment by sakshi2912** [comment]
> a timer has been added to the hangman game..
> 
> a word of length b/w 0 and 5 => 60 secs
> a word of length b/w 5 and 10 => 120 secs
> a word of length 10 and above => 300 secs
> 
> also, you can decrease the timer for testing so as to save time :)

Hey @Prajwal220. When I tried running the code , it gave 120 seconds for a 4 letter word.( Although it is supposed to be 60)
Please check this output for your reference.
image

Also, after the timeout tell the user what the word was. 
This is what is happening currently:
image

**Comment by Prajwal2204** [comment]
Oh okay, I'll check it again. Sorry..

**Comment by sakshi2912** [comment]
> Oh okay, I'll check it again. Sorry..

No worries :)

**Comment by Prajwal2204** [comment]
Hey @sakshi2912, I think I have solved that issue, could you please check my latest commit on the same pull request and confirm?
Thank you.

**Comment by sakshi2912** [comment]
> Hey @sakshi2912, I think I have solved that issue, could you please check my latest commit on the same pull request and confirm?
> Thank you.

hey @Prajwal2204 , the first two things i mentioned were taken care of. But when the user runs out of time, this is what is happening:
image

It is still waiting for an input from the user, and an error is thrown. If you could terminate that loop and re-display the menu to continue or start a new game, it would be good.

**Comment by Prajwal2204** [comment]
done

**Comment by sakshi2912** [comment]
Great!

**Comment by sakshi2912** [comment]
!bounty 110

**Pull request closed without merging**
